name: docker-container-node-executor
version: 1.1.0
rundeckPluginVersion: 1.2
author: alexh
date: Thu Aug  6 19:32:08 PDT 2015
providers:
  - name: docker-container-execute-command
    service: WorkflowNodeStep
    title: docker / container / execute
    description: 'execute the command in the container'
    plugin-type: script
    script-interpreter: python -u
    script-file: node-execute
    script-args: ${config.container} ${config.user} ${config.command}
    config:
      - type: String
        name: container
        title: 'container'
        description: "the container to dispatch the command"
        required: true
      - type: String
        name: command
        title: 'command'
        description: "the command string to execute in the container"
        required: true
      - type: String
        name: user
        title: 'User'
        description: "User to execute command as."
        default: root
        required: true
      - type: String
        name: docker-cert-path
        title: 'docker-cert-path'
        description: "the certificate path"
        renderingOptions:
          grouping: secondary
          groupName: 'API Connection'
      - type: String
        name: docker-host
        title: 'docker-host'
        description: "the docker host"
        renderingOptions:
          grouping: secondary
          groupName: 'API Connection'
      - type: Select
        name: docker-tls-verify
        title: 'docker-tls-verify'
        description: "verify TLS"
        default: '1'
        values: 1,0
        renderingOptions:
          grouping: secondary
          groupName: 'API Connection'
  - name: docker-container-node-executor
    service: NodeExecutor
    title: docker-container-node-executor
    description: 'dispatch the command to the container'
    plugin-type: script
    script-interpreter: python -u
    script-file: node-execute
    script-args: ${node.docker:Id} ${node.username} ${exec.command}
    config:
      - type: String
        name: docker-cert-path
        title: 'docker-cert-path'
        description: "the certificate path"
      - type: String
        name: docker-host
        title: 'docker-host'
        description: "the docker host"
      - type: Select
        name: docker-tls-verify
        title: 'docker-tls-verify'
        description: "verify TLS"
        values: 1,0
      - type: String
        name: container
        title: 'container'
        description: "the container to dispatch."
  - name: docker-container-model-source
    service: ResourceModelSource
    resource-format: resourcejson
    title: docker / container / model
    description: 'read docker containers as Nodes'
    plugin-type: script
    script-interpreter: python -u
    script-file: model-source
    script-args: ${config.attributes} ${config.tags}
    config:
      - type: String
        name: docker-cert-path
        title: 'docker-cert-path'
        description: "the certificate path"
      - type: String
        name: docker-host
        title: 'docker-host'
        description: "the docker host"
      - type: Select
        name: docker-tls-verify
        title: 'docker-tls-verify'
        description: "verify TLS"
        values: 1,0
      - type: String
        name: attributes
        title: 'Default attributes'
        description: "List of key=value pairs"
      - type: String
        name: tags
        title: Tags
        description: "List of tags"
      - type: Boolean
        name: debug
        title: Debug?
        description: "Write debug messages to stderr"
  - name: docker-container-inspect-workflow-step
    service: WorkflowNodeStep
    title: docker / container / inspect
    description: 'inspect the state of the container'
    plugin-type: script
    script-interpreter: python -u
    script-file: container-inspect
    script-args: ${config.container}
    config:
      - type: String
        name: container
        description: "The container ID"
  - name: docker-container-pause-step
    service: WorkflowNodeStep
    title: docker / container / pause
    description: 'pause all processes within the container'
    plugin-type: script
    script-interpreter: python -u
    script-file: container-pause
    script-args: ${config.container}
    config:
      - type: String
        name: container
        description: "The container ID"
  - name: docker-container-unpause-step
    service: WorkflowNodeStep
    title: docker / container / unpause
    description: 'unpause all processes within the container'
    plugin-type: script
    script-interpreter: python -u
    script-file: container-unpause
    script-args: ${config.container}
    config:
      - type: String
        name: container
        description: "The container ID"
  - name: docker-container-kill-step
    service: WorkflowNodeStep
    title: docker / container / kill
    description: 'kill the running container'
    plugin-type: script
    script-interpreter: python -u
    script-file: container-kill
    script-args: ${config.container} ${container.signal}
    config:
      - type: String
        name: container
        description: "The container ID"
      - type: String
        name: signal
        description: "Signal to send to the container"
        default: KILL
  - name: docker-container-stats-step
    service: WorkflowNodeStep
    title: docker / container / stats
    description: 'Display container resource usage statistics (no-stream)'
    plugin-type: script
    script-interpreter: python -u
    script-file: container-stats
    script-args: ${config.container} ${config.format}
    config:
      - type: String
        name: container
        description: "The container ID"
      - type: String
        name: format
        description: "Pretty-print images using a Go template"
        default: 'table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}'
  - name: docker-run-workflow-step
    service: WorkflowNodeStep
    title: docker / image / run
    description: 'run the image'
    plugin-type: script
    script-interpreter: python -u
    script-file: run-image
    script-args: ${config.image} ${config.command}
    config:
      - type: String
        name: add-host
        title: 'add-host'
        description: "Add a line to /etc/hosts (host:IP)"
      - type: Integer
        name: blkio-weight
        title: 'blkio-weight'
        description: "Block IO weight (relative weight) accepts a weight value between 10 and 1000."
      - type: String
        name: cap-add
        title: 'cap-add'
        description: "Add Linux capabilities"
      - type: String
        name: cap-drop
        title: 'cap-drop'
        description: "Drop Linux capabilities"
      - type: String
        name: cidfile
        title: 'cidfile'
        description: "Write the container ID to the file"
      - type: String
        name: command
        title: 'command'
        description: "Run this command at start up"
      - type: Integer
        name: cpu-period
        title: 'cpu-period'
        description: "Limit the CPU CFS (Completely Fair Scheduler) period"
      - type: Integer
        name: cpu-quota
        title: 'cpu-quota'
        description: "Limit the CPU CFS (Completely Fair Scheduler) quota"
      - type: Integer
        name: cpu-shares
        title: 'cpu-shares'
        description: "CPU shares (relative weight)"
      - type: String
        name: cpuset-cpus
        title: 'cpuset-cpus'
        description: "CPUs in which to allow execution (0-3, 0,1)"
      - type: String
        name: cpuset-mems
        title: 'cpuset-mems'
        description: "Memory nodes (MEMs) in which to allow execution (0-3, 0,1)"
      - type: Select
        name: detach
        title: 'detach'
        description: "Run container in background and print container ID"
        values: true,false
      - type: String
        name: device
        title: 'device'
        description: "Allows you to run devices inside the container without the --privileged flag"
      - type: String
        name: dns
        title: 'dns'
        description: "Set custom dns servers for the container"
      - type: String
        name: env
        title: 'environment variables'
        description: "Set of environment variables."
      - type: String
        name: image
        title: 'image'
        description: "The container image identifier"
        required: true
      - type: FreeSelect
        name: ipc
        title: 'ipc'
        description: "Set the IPC mode for the container"
        values: host,container:<name|id>
      - type: Select
        name: log-driver
        title: 'log-driver'
        description: "Logging driver for container"
        values: none,json-file,syslog,journald
      - type: String
        name: log-opt
        title: 'log-opt'
        description: "Log driver options"
      - type: String
        name: lxc-conf
        title: 'lxc-conf'
        description: "Add custom lxc options"
      - type: String
        name: memory
        title: 'memory'
        description: "Memory limit (format: <number><optional unit>, where unit = b, k, m or g)"
      - type: String
        name: memory-swap
        title: 'memory-swap'
        description: "Total memory limit (memory + swap, format: <number><optional unit>, where unit = b, k, m or g)"
      - type: String
        name: name
        title: 'name'
        description: "the identifying name"
      - type: FreeSelect
        name: net
        title: 'net'
        description: "Set the Network mode for the container"
        values: bridge,none,host,container:<name|id>
      - type: Select
        name: oom-kill-disable
        title: 'oom-kill-disable'
        description: "Whether to disable OOM Killer for the container or not."
        values: true,false
      - type: Select
        name: privileged
        title: 'privileged'
        description: "Give extended privileges to this container"
        values: true,false
      - type: String
        name: publish
        title: 'publish'
        description: "Publish a container port (eg xxxx:yyyy)"
      - type: FreeSelect
        name: restart
        title: 'restart'
        description: "Restart policy to apply when a container exits"
        values: no,always,on-failure[:max-retries]
      - type: Select
        name: rm
        title: 'rm'
        description: "Automatically remove the container when it exits"
        values: true,false
      - type: String
        name: security-opt
        title: 'security-opt'
        description: "Security Options"
      - type: String
        name: read-only
        title: 'read-only'
        description: "Mount the container's root filesystem as read only"
      - type: String
        name: volume
        title: 'volume'
        description: "Bind mount a volume"
      - type: String
        name: volumes-from
        title: 'volumes-from'
        description: "Mount volumes from the specified container(s)"
      - type: String
        name: ulimit
        title: 'ulimit'
        description: "Ulimit options"
      - type: String
        name: uts
        title: 'uts'
        description: "UTS namespace to use"
      - type: String
        name: label
        title: 'label'
        description: "Set meta data on a container"
      - type: Select
        name: interactive
        title: 'interactive'
        description: "Keep STDIN open even if not attached"
        values: true,false
      - type: Select
        name: tty
        title: 'tty'
        description: "Allocate a pseudo-TTY"
        values: true,false
      - type: String
        name: docker-cert-path
        title: 'docker-cert-path'
        description: "the certificate path"
        renderingOptions:
          grouping: secondary
          groupName: 'API Connection'
      - type: String
        name: docker-host
        title: 'docker-host'
        description: "the docker host"
        renderingOptions:
          grouping: secondary
          groupName: 'API Connection'
      - type: Select
        name: docker-tls-verify
        title: 'docker-tls-verify'
        description: "verify TLS"
        values: 1,0
        renderingOptions:
          grouping: secondary
          groupName: 'API Connection'
