#!/usr/bin/env python -u
import argparse
import logging
import shlex
import sys
import os
import json
from subprocess import Popen, PIPE

if os.environ.get('RD_CONFIG_DEBUG') == 'true':
    log_level = 'DEBUG'
else:
    log_level = 'ERROR'

logging.basicConfig(
    stream=sys.stderr,
    level=getattr(logging, log_level),
    format='%(levelname)s: %(name)s: %(message)s'
)
log = logging.getLogger('container-model-source')

class JsonQuery(dict):
    def get(self, path, default = None):
        keys = path.split(".")
        val = None

        for key in keys:
            if val:
                if isinstance(val, list):
                    val = [ v.get(key, default) if v else None for v in val]
                else:
                    val = val.get(key, default)
            else:
                val = dict.get(self, key, default)

            if not val:
                break;

        return val


def nodeCollectData(containerId, json, defaults, taglist, mappingList):
    log.debug('Parsing json data for container: %s' % containerId)
    tags = []
    tags.extend(taglist.split(','))

    ip=json[0]["NetworkSettings"]["IPAddress"]

    #docker-compose has a different json format
    if not ip:
        networkArray=json[0]["NetworkSettings"]["Networks"]
        for key, value in networkArray.items():
            ip=value["IPAddress"]

    default_settings = {
        'default:Id': json[0]["Id"],
        'default:Created': json[0]["Created"],
        'default:Name': json[0]["Name"],
        'default:Image': json[0]["Image"],
        'default:State.Status': json[0]["State"]["Status"],
        'default:State.Pid': json[0]["State"]["Pid"],
        'default:State.StartedAt': json[0]["State"]["StartedAt"],
        'default:Config.Image': json[0]["Config"]["Image"],
        'default:Config.Hostname': json[0]["Config"]["Hostname"],
        'default:Config.Cmd': json[0]["Config"]["Cmd"][0],
        'default:Config.Labels': json[0]["Config"]["Labels"],
        'default:IPAddress': ip,
    }

    mappings = []
    custom_attributes={}

    #custom mapping attributes
    if mappingList:
        log.debug('Mapping: %s' % mappingList)
        mappings.extend(mappingList.split(','))

        for mapping in mappings:
            mapping_array = dict(s.split('=', 1) for s in mapping.split())

            for key, value in mapping_array.items():
                if key.find(".selector"):

                    attribute= key.replace(".selector" ,"")
                    custom_attribute=None
                    
                    #take the values from default
                    if "default:" in value:
                        custom_attribute=default_settings[value]
                    else:
                    #taking the values from docker inspect
                        for item in json:
                            custom_attribute=JsonQuery(item).get(value)

                    if custom_attribute:
                        custom_attributes[attribute] = custom_attribute

        log.debug('Custom Attributes: %s' % custom_attributes)

    # rundeck attributes
    data = default_settings
    data['nodename']=containerId
    data['hostname']=json[0]["Config"]["Hostname"]
    
    final_tags = ['docker']
    for tag in tags:        
        if "tag.selector=" in tag:
            custom_tag=data[tag.replace("tag.selector=" ,"")]
            final_tags.append(custom_tag)
        else:
            final_tags.append(tag)

    data['tags'] = ','.join(final_tags)

    if custom_attributes:
        data = dict(data.items() + custom_attributes.items())

    data.update(dict(token.split('=') for token in shlex.split(defaults)))

    return data


parser = argparse.ArgumentParser(
    description='Execute a command string in the container.'
)

parser.add_argument('defaults', help='key=value list')
parser.add_argument('tags', help='comma separated list of additonal tags')

args = parser.parse_args()

if 'RD_CONFIG_DOCKER_HOST' in os.environ:
    os.environ['DOCKER_HOST'] = os.environ['RD_CONFIG_DOCKER_HOST']
    log.debug('DOCKER_HOST set to %s' % os.environ['RD_CONFIG_DOCKER_HOST'])
else:
    log.debug('RD_CONFIG_DOCKER_HOST environment variable not defined.')

if 'RD_CONFIG_DOCKER_CERT_PATH' in os.environ:
    os.environ['DOCKER_CERT_PATH'] = os.environ['RD_CONFIG_DOCKER_CERT_PATH']
    log.debug('DOCKER_CERT_PATH=%s' % os.environ['RD_CONFIG_DOCKER_CERT_PATH'])
else:
    log.debug('RD_CONFIG_DOCKER_CERT_PATH environment variable not defined.')

if 'RD_CONFIG_DOCKER_TLS_VERIFY' in os.environ:
    os.environ['DOCKER_TLS_VERIFY'] = os.environ['RD_CONFIG_DOCKER_TLS_VERIFY']
    log.debug(
        'DOCKER_TLS_VERIFY=%s' % os.environ['RD_CONFIG_DOCKER_TLS_VERIFY']
    )
else:
    log.debug(
        'RD_CONFIG_DOCKER_TLS_VERIFY environment variable not defined.'
    )

mappingList=None

if 'RD_CONFIG_MAPPING' in os.environ:
    mappingList= os.environ['RD_CONFIG_MAPPING']

log.debug('Mapping: %s' % mappingList)

# Get a listing of the docker containers
log.debug('Executing `docker ps --format {{.ID}}` ...')
ps = Popen(
    'docker ps --format "{{.ID}}"',
    shell=True,
    stdout=PIPE,
    stderr=PIPE,
    bufsize=1,
    universal_newlines=True
)
exitcode = ps.wait()

if exitcode != 0:
    log.error('Failure from docker ps command (exitcode: %s)' % str(exitcode))
    sys.exit(exitcode)

containers = ps.stdout.readlines()
log.debug('Processing %d containers ...' % len(containers))
node_set = []

for container in containers:
    log.debug('Inspecting container: %s' % container)
    inspect = Popen(
        shlex.split('docker inspect %s ' % container),
        shell=False,
        stdout=PIPE,
        stderr=PIPE,
        bufsize=1,
        universal_newlines=True
    )
    inspect_json = json.load(inspect.stdout)
    node_data = nodeCollectData(
        container.rstrip('\n'),
        inspect_json,
        args.defaults,
        args.tags,
        mappingList
    )
    node_set.append(node_data)

# done
print(json.dumps(node_set, indent=4, sort_keys=True))
