#!/usr/bin/env python -u
import argparse
import logging
import shlex
import sys
import os
from subprocess import Popen, PIPE, STDOUT
import threading

if os.environ.get('RD_CONFIG_DEBUG') == 'true':
    log_level = 'DEBUG'
else:
    log_level = 'ERROR'

logging.basicConfig(
    stream=sys.stdout,
    level=getattr(logging, log_level),
    format='%(levelname)s: %(name)s: %(message)s'
)
log = logging.getLogger('docker-run')


def stdoutprocess(o):
   while True:
      stdoutdata = o.stdout.readline()
      if stdoutdata:
         print(stdoutdata.decode())
      else:
         break


def stderrprocess(o):
   while True:
      stderrdata = o.stderr.readline()
      if stderrdata:
         log.error(stderrdata.decode())
      else:
         break


parser = argparse.ArgumentParser(
    description='Start a container with the specified image.'
)
parser.add_argument('image', help='the image to run')
parser.add_argument('command', help='the command to run')
args = parser.parse_args()

possible_opts = ['add-host', 'blkio-weight', 'cap-add', 'cap-drop', 'cidfile',
                 'cpu-shares', 'cpu-period', 'cpuset-cpus', 'cpuset-mems',
                 'cpu-quota', 'detach', 'device', 'dns', 'env', 'interactive',
                 'ipc', 'label', 'log-driver', 'log-opt', 'lxc-conf', 'memory',
                 'memory-swap', 'name', 'net', 'oom-kill-disable', 'publish',
                 'privileged', 'restart', 'rm', 'security-opt', 'volume',
                 'volume-from', 'ulimit', 'uts', 'tty', 'workdir', 'user']
OPTIONS = []

for env_var_name, env_var_value in os.environ.items():
    if (env_var_name.startswith('RD_OPTION') or
       env_var_name.startswith('RD_NODE') or
       env_var_name.startswith('RD_JOB')) and \
       env_var_value:
        OPTIONS.append("--env=%s='%s'" % (env_var_name, env_var_value))
        log.debug(
            "appended option: --env=%s='%s'" % (env_var_name, env_var_value)
        )

for opt in possible_opts:
    env_var_name = "RD_CONFIG_%s" % opt.upper().replace('-', '_')
    if env_var_name in os.environ:
        for env_var_value in shlex.split(os.environ[env_var_name]):
            OPTIONS.append("--%s='%s'" % (opt, env_var_value))
            log.debug("appended option: --%s='%s'" % (opt, env_var_value))


detach = False
if 'RD_CONFIG_DETACH' in os.environ:
    detachValue = os.environ['RD_CONFIG_DETACH']
    if detachValue == "true":
        detach = True

if 'RD_CONFIG_DOCKER_HOST' in os.environ:
    os.environ['DOCKER_HOST'] = os.environ['RD_CONFIG_DOCKER_HOST']
    log.debug('DOCKER_HOST set to %s' % os.environ['RD_CONFIG_DOCKER_HOST'])
else:
    log.debug('RD_CONFIG_DOCKER_HOST environment variable not defined.')

if 'RD_CONFIG_DOCKER_CERT_PATH' in os.environ:
    os.environ['DOCKER_CERT_PATH'] = os.environ['RD_CONFIG_DOCKER_CERT_PATH']
    log.debug('DOCKER_CERT_PATH=%s' % os.environ['RD_CONFIG_DOCKER_CERT_PATH'])
else:
    log.debug('RD_CONFIG_DOCKER_CERT_PATH environment variable not defined.')

if 'RD_CONFIG_DOCKER_TLS_VERIFY' in os.environ:
    os.environ['DOCKER_TLS_VERIFY'] = os.environ['RD_CONFIG_DOCKER_TLS_VERIFY']
    log.debug(
        'DOCKER_TLS_VERIFY=%s' % os.environ['RD_CONFIG_DOCKER_TLS_VERIFY']
    )
else:
    log.debug(
        'RD_CONFIG_DOCKER_TLS_VERIFY environment variable not defined.'
    )

if args.command in {'${option.command}', '${config.command}'}:
    args.command = None

COMMAND = ['docker', 'run']
COMMAND.extend(OPTIONS)
COMMAND.append(args.image)

if args.command is not None:
    COMMAND.append(args.command)

command_string = " ".join(COMMAND)
log.debug("Executing: '%s' ..." % command_string)

p = Popen(
    shlex.split(command_string),
    shell=False,
    stdout=PIPE,
    stderr=PIPE
)

returncode = 0
if detach:
    std_out, std_err = p.communicate()
    returncode = p.returncode

    if p.returncode != 0:
        # an error happened!
        err_msg = "%s. Code: %s" % (std_err.strip().decode(), p.returncode)
        log.error(err_msg)

    elif len(std_err):
        # return code is 0 (no error), but we may want to
        # do something with the info on std_err
        # i.e. logger.warning(std_err)
        log.warn(std_err)

    if returncode == 0:
        print("id: %s" % std_out.strip().decode())
else:
    log.debug("Starting container, waiting for output")
    #live output

    t = threading.Thread(target=stdoutprocess, args=(p,))
    t.start()
    t.join()

    terror = threading.Thread(target=stderrprocess, args=(p,))
    terror.start()
    terror.join()

    p.wait()

    returncode = p.returncode

if returncode != 0:
    log.error('Command execution failed with exit code: %s' % str(returncode))

# done
sys.exit(returncode)
