name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Fetch Tags
      run: git -c protocol.version=2 fetch --tags --progress --no-recurse-submodules origin
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Release Version
      id: get_version
      run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo ::set-output name=VERSION::$VERSION
    - name: Upload docker zip
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: docker-${{ steps.get_version.outputs.VERSION }}
        # Directory containing files to upload
        path: ./build/libs/docker-${{ steps.get_version.outputs.VERSION }}.zip
